from django.urls import path

from pages import views


urlpatterns = [
    path("", views.page("home/html/index.html"), name="home"),
    path("home/", views.page("home/html/index.html"), name="home-page"),
    path("hotels/", views.page("hotels/html/hotels.html"), name="hotels"),
    path("hotels/detail/", views.page("hotels/html/hotel-detail.html"), name="hotel-detail"),
    path("offers/", views.page("offers/html/offers.html"), name="offers"),
    path("destinations/", views.page("destinations/html/destinations.html"), name="destinations"),
    path("contact/", views.page("contact/html/contact.html"), name="contact"),
    path("about/", views.page("about/html/about.html"), name="about"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/signup/", views.signup_view, name="signup"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/forgot-password/", views.page("auth/html/forgot-password.html"), name="forgot-password"),
    path("auth/reset-password/", views.page("auth/html/reset-password.html"), name="reset-password"),
    path("checkout/guest-details/", views.page("checkout/html/guest-details.html"), name="guest-details"),
    path("checkout/payment/", views.page("checkout/html/payment.html"), name="payment"),
    path("checkout/booking-confirmed/", views.page("checkout/html/booking-confirmed.html"), name="booking-confirmed"),
    path("dashboard/", views.page("dashboard/html/index.html", require_login=True), name="dashboard"),
    path("dashboard/bookings/", views.page("dashboard/html/bookings.html", require_login=True), name="dashboard-bookings"),
    path("dashboard/saved/", views.page("dashboard/html/saved.html", require_login=True), name="dashboard-saved"),
    path("dashboard/profile/", views.page("dashboard/html/profile.html", require_login=True), name="dashboard-profile"),
    path("dashboard/notifications/", views.page("dashboard/html/notifications.html", require_login=True), name="dashboard-notifications"),
    path("dashboard/payment-methods/", views.page("dashboard/html/payment-methods.html", require_login=True), name="dashboard-payment-methods"),
    path("dashboard/reviews/", views.page("dashboard/html/reviews.html", require_login=True), name="dashboard-reviews"),
    path("dashboard/rewards/", views.page("dashboard/html/rewards.html", require_login=True), name="dashboard-rewards"),
    # Legacy frontend paths kept working so old links/bookmarks do not break.
    path("home/html/index.html", views.page("home/html/index.html")),
    path("hotels/html/hotels.html", views.page("hotels/html/hotels.html")),
    path("hotels/html/hotel-detail.html", views.page("hotels/html/hotel-detail.html")),
    path("offers/html/offers.html", views.page("offers/html/offers.html")),
    path("destinations/html/destinations.html", views.page("destinations/html/destinations.html")),
    path("contact/html/contact.html", views.page("contact/html/contact.html")),
    path("about/html/about.html", views.page("about/html/about.html")),
    path("auth/html/login.html", views.login_view),
    path("auth/html/signup.html", views.signup_view),
    path("auth/html/forgot-password.html", views.page("auth/html/forgot-password.html")),
    path("auth/html/reset-password.html", views.page("auth/html/reset-password.html")),
    path("checkout/html/guest-details.html", views.page("checkout/html/guest-details.html")),
    path("checkout/html/payment.html", views.page("checkout/html/payment.html")),
    path("checkout/html/booking-confirmed.html", views.page("checkout/html/booking-confirmed.html")),
    path("dashboard/html/index.html", views.page("dashboard/html/index.html", require_login=True)),
    path("dashboard/html/bookings.html", views.page("dashboard/html/bookings.html", require_login=True)),
    path("dashboard/html/saved.html", views.page("dashboard/html/saved.html", require_login=True)),
    path("dashboard/html/profile.html", views.page("dashboard/html/profile.html", require_login=True)),
    path("dashboard/html/notifications.html", views.page("dashboard/html/notifications.html", require_login=True)),
    path("dashboard/html/payment-methods.html", views.page("dashboard/html/payment-methods.html", require_login=True)),
    path("dashboard/html/reviews.html", views.page("dashboard/html/reviews.html", require_login=True)),
    path("dashboard/html/rewards.html", views.page("dashboard/html/rewards.html", require_login=True)),
]
