from django.contrib import admin
from django.urls import path

from pages import views


urlpatterns = [
    path("service-worker.js", views.service_worker_view, name="service-worker"),
    path("admin/", admin.site.urls),
    path("", views.page("home/html/index.html"), name="home"),
    path("home/", views.page("home/html/index.html"), name="home-page"),
    path("api/hotels/", views.hotels_api, name="hotels-api"),
    path("hotels/", views.hotels_view, name="hotels"),
    path("hotels/detail/", views.page("hotels/html/hotel-detail.html"), name="hotel-detail"),
    path("offers/", views.page("offers/html/offers.html"), name="offers"),
    path("destinations/", views.page("destinations/html/destinations.html"), name="destinations"),
    path("contact/", views.page("contact/html/contact.html"), name="contact"),
    path("about/", views.page("about/html/about.html"), name="about"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/signup/", views.signup_view, name="signup"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/forgot-password/", views.page("auth/html/forgot-password.html"), name="forgot-password"),
    path("auth/reset-password/", views.page("auth/html/reset-password.html"), name="reset-password"),
    path("checkout/guest-details/", views.guest_details_view, name="guest-details"),
    path("checkout/payment/", views.payment_view, name="payment"),
    path("checkout/booking-confirmed/", views.booking_confirmed_view, name="booking-confirmed"),
    path("dashboard/", views.dashboard_overview_view, name="dashboard"),
    path("dashboard/bookings/", views.dashboard_bookings_view, name="dashboard-bookings"),
    path("dashboard/saved/", views.dashboard_saved_view, name="dashboard-saved"),
    path("dashboard/profile/", views.dashboard_profile_view, name="dashboard-profile"),
    path("dashboard/notifications/", views.dashboard_notifications_view, name="dashboard-notifications"),
    path("dashboard/payment-methods/", views.dashboard_payment_methods_view, name="dashboard-payment-methods"),
    path("dashboard/reviews/", views.dashboard_reviews_view, name="dashboard-reviews"),
    path("dashboard/rewards/", views.dashboard_rewards_view, name="dashboard-rewards"),
    path("dashboard/saved/toggle/", views.toggle_saved_hotel_view, name="toggle-saved-hotel"),
    # Legacy frontend paths kept working so old links/bookmarks do not break.
    path("home/html/index.html", views.page("home/html/index.html")),
    path("hotels/html/hotels.html", views.hotels_view),
    path("hotels/html/hotel-detail.html", views.page("hotels/html/hotel-detail.html")),
    path("offers/html/offers.html", views.page("offers/html/offers.html")),
    path("destinations/html/destinations.html", views.page("destinations/html/destinations.html")),
    path("contact/html/contact.html", views.page("contact/html/contact.html")),
    path("about/html/about.html", views.page("about/html/about.html")),
    path("auth/html/login.html", views.login_view),
    path("auth/html/signup.html", views.signup_view),
    path("auth/html/forgot-password.html", views.page("auth/html/forgot-password.html")),
    path("auth/html/reset-password.html", views.page("auth/html/reset-password.html")),
    path("checkout/html/guest-details.html", views.guest_details_view),
    path("checkout/html/payment.html", views.payment_view),
    path("checkout/html/booking-confirmed.html", views.booking_confirmed_view),
    path("dashboard/html/index.html", views.dashboard_overview_view),
    path("dashboard/html/bookings.html", views.dashboard_bookings_view),
    path("dashboard/html/saved.html", views.dashboard_saved_view),
    path("dashboard/html/profile.html", views.dashboard_profile_view),
    path("dashboard/html/notifications.html", views.dashboard_notifications_view),
    path("dashboard/html/payment-methods.html", views.dashboard_payment_methods_view),
    path("dashboard/html/reviews.html", views.dashboard_reviews_view),
    path("dashboard/html/rewards.html", views.dashboard_rewards_view),
]
