# Generated by Django 5.2.11 on 2026-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Turkey', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('property_type', models.CharField(default='hotel', max_length=50)),
                ('amenities', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('original_price', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('max_guests', models.PositiveIntegerField(default=4)),
                ('rooms_left', models.PositiveIntegerField(default=5)),
            ],
            options={
                'ordering': ['current_price', 'name'],
            },
        ),
    ]
