from django.db import migrations


HOTELS = [
    {
        "code": "h1",
        "name": "Azure Coast Resort & Spa",
        "city": "Antalya",
        "country": "Turkey",
        "location": "Antalya Beachfront, Turkey",
        "category": "beach",
        "property_type": "resort",
        "amenities": "Pool, WiFi, Spa, Beach Access",
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
        "rating": "4.8",
        "review_count": 1240,
        "original_price": 320,
        "current_price": 240,
        "max_guests": 5,
        "rooms_left": 4,
    },
    {
        "code": "h2",
        "name": "Grand Bosphorus Hotel",
        "city": "Istanbul",
        "country": "Turkey",
        "location": "Istanbul, Turkey",
        "category": "city",
        "property_type": "hotel",
        "amenities": "Pool, WiFi, Spa, Restaurant",
        "image_url": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
        "rating": "4.7",
        "review_count": 892,
        "original_price": 310,
        "current_price": 224,
        "max_guests": 4,
        "rooms_left": 3,
    },
    {
        "code": "h3",
        "name": "Cappadocia Cave Suites",
        "city": "Cappadocia",
        "country": "Turkey",
        "location": "Cappadocia, Turkey",
        "category": "historical",
        "property_type": "boutique",
        "amenities": "WiFi, Restaurant, Parking, Hot Air Balloon View",
        "image_url": "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=600&q=80",
        "rating": "4.7",
        "review_count": 850,
        "original_price": 210,
        "current_price": 126,
        "max_guests": 3,
        "rooms_left": 5,
    },
    {
        "code": "h4",
        "name": "Bodrum Marina Villas",
        "city": "Bodrum",
        "country": "Turkey",
        "location": "Bodrum Marina, Turkey",
        "category": "resort",
        "property_type": "villa",
        "amenities": "Pool, WiFi, Parking, Beach Access",
        "image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
        "rating": "4.6",
        "review_count": 614,
        "original_price": 280,
        "current_price": 196,
        "max_guests": 6,
        "rooms_left": 2,
    },
    {
        "code": "h5",
        "name": "Trabzon Highland Lodge",
        "city": "Trabzon",
        "country": "Turkey",
        "location": "Trabzon Highlands, Turkey",
        "category": "mountain",
        "property_type": "hotel",
        "amenities": "WiFi, Parking, Restaurant, Mountain View",
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
        "rating": "4.5",
        "review_count": 433,
        "original_price": 180,
        "current_price": 135,
        "max_guests": 4,
        "rooms_left": 6,
    },
    {
        "code": "h6",
        "name": "Dubai Skyline Palace",
        "city": "Dubai",
        "country": "United Arab Emirates",
        "location": "Downtown Dubai, United Arab Emirates",
        "category": "city",
        "property_type": "hotel",
        "amenities": "Pool, WiFi, Spa, Gym, Restaurant",
        "image_url": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
        "rating": "4.9",
        "review_count": 1504,
        "original_price": 460,
        "current_price": 345,
        "max_guests": 4,
        "rooms_left": 7,
    },
    {
        "code": "h7",
        "name": "Bali Serenity Retreat",
        "city": "Bali",
        "country": "Indonesia",
        "location": "Ubud, Bali, Indonesia",
        "category": "spa",
        "property_type": "resort",
        "amenities": "Pool, WiFi, Spa, Restaurant",
        "image_url": "https://images.unsplash.com/photo-1476517865536-07fb390edeee?w=600&q=80",
        "rating": "4.8",
        "review_count": 978,
        "original_price": 260,
        "current_price": 182,
        "max_guests": 4,
        "rooms_left": 4,
    },
    {
        "code": "h8",
        "name": "Paris Boutique Maison",
        "city": "Paris",
        "country": "France",
        "location": "Saint-Germain, Paris, France",
        "category": "city",
        "property_type": "boutique",
        "amenities": "WiFi, Restaurant, Spa",
        "image_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
        "rating": "4.6",
        "review_count": 721,
        "original_price": 390,
        "current_price": 292,
        "max_guests": 3,
        "rooms_left": 5,
    },
    {
        "code": "h9",
        "name": "Maldives Lagoon Hideaway",
        "city": "Maldives",
        "country": "Maldives",
        "location": "North Male Atoll, Maldives",
        "category": "beach",
        "property_type": "resort",
        "amenities": "Pool, WiFi, Spa, Beach Access, Restaurant",
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
        "rating": "4.9",
        "review_count": 1128,
        "original_price": 520,
        "current_price": 390,
        "max_guests": 5,
        "rooms_left": 3,
    },
]


def seed_hotels(apps, schema_editor):
    Hotel = apps.get_model("pages", "Hotel")
    for hotel in HOTELS:
        Hotel.objects.update_or_create(code=hotel["code"], defaults=hotel)


def remove_hotels(apps, schema_editor):
    Hotel = apps.get_model("pages", "Hotel")
    Hotel.objects.filter(code__in=[hotel["code"] for hotel in HOTELS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_hotels, remove_hotels),
    ]
